# Student Name: Cian O'Connor
# Student Number: x22109668
# Module: Final Year Project

# Generated by Django 6.0.1 on 2026-05-12 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("USER_CREATED", "User created"),
                            ("USER_UPDATED", "User updated"),
                            ("USER_DEACTIVATED", "User deactivated"),
                            ("USER_REACTIVATED", "User reactivated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_type", models.CharField(max_length=100)),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("target_repr", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
