# Generated by Django 6.0.1 on 2026-07-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_FAILED", "Login failed"),
                    ("LOGIN_RATE_LIMITED", "Login rate limited"),
                    ("ACCESS_DENIED", "Access denied"),
                    ("UPLOAD_BLOCKED", "Upload blocked"),
                    ("USER_CREATED", "User created"),
                    ("USER_UPDATED", "User updated"),
                    ("USER_DEACTIVATED", "User deactivated"),
                    ("USER_REACTIVATED", "User reactivated"),
                    ("TICKET_CREATED", "Ticket created"),
                    ("TICKET_STATUS_CHANGED", "Ticket status changed"),
                    ("TICKET_ASSIGNED", "Ticket assigned"),
                    ("TICKET_PRIORITY_CHANGED", "Ticket priority changed"),
                    ("TICKET_RESOLVED", "Ticket resolved"),
                    ("TICKET_CANCELLED", "Ticket cancelled"),
                    ("TICKET_COMMENT_ADDED", "Ticket comment added"),
                    ("RESOLUTION_NOTE_ADDED", "Resolution note added"),
                ],
                max_length=50,
            ),
        ),
    ]
