# Generated by Django 6.0.1 on 2026-07-19 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0003_alter_auditlog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="low",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_FAILED", "Login failed"),
                    ("LOGIN_RATE_LIMITED", "Login rate limited"),
                    ("ACCESS_DENIED", "Access denied"),
                    ("UPLOAD_BLOCKED", "Upload blocked"),
                    ("USER_CREATED", "User created"),
                    ("USER_UPDATED", "User updated"),
                    ("USER_DEACTIVATED", "User deactivated"),
                    ("USER_REACTIVATED", "User reactivated"),
                    ("TICKET_CREATED", "Ticket created"),
                    ("TICKET_STATUS_CHANGED", "Ticket status changed"),
                    ("TICKET_ASSIGNED", "Ticket assigned"),
                    ("TICKET_PRIORITY_CHANGED", "Ticket priority changed"),
                    ("TICKET_RESOLVED", "Ticket resolved"),
                    ("TICKET_CANCELLED", "Ticket cancelled"),
                    ("TICKET_COMMENT_ADDED", "Ticket comment added"),
                    ("RESOLUTION_NOTE_ADDED", "Resolution note added"),
                    ("AI_CATEGORY_OVERRIDDEN", "AI category overridden"),
                    ("SECURITY_TICKET_FLAGGED", "Security ticket flagged"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["flagged", "-created_at"], name="admin_porta_flagged_e1a6e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["severity", "-created_at"],
                name="admin_porta_severit_4069c4_idx",
            ),
        ),
    ]
