# Student Name: Cian O'Connor
# Student Number: x22109668
# Module: Final Year Project

# Generated by Django 6.0.1 on 2026-04-07 13:52

from django.db import migrations

# Seeding initial lookup data for TicketType, TicketSystem, TicketPriority, and TicketStatus models
def seed_lookup_data(apps, schema_editor):
        TicketType = apps.get_model("tickets", "TicketType")
        TicketSystem = apps.get_model("tickets", "TicketSystem")
        TicketPriority = apps.get_model("tickets", "TicketPriority")
        TicketStatus = apps.get_model("tickets", "TicketStatus")

        # Seed Ticket Types
        ticket_types = [
            {"name": "Incident", "code": "INCIDENT", "description": "An unplanned issue or service disruption that needs to be resolved.", "sort_order": 1},
            {"name": "Service Request", "code": "SERVICE", "description": "A request for routine support, assistance, or a standard IT service.", "sort_order": 2},
            {"name": "Access Request", "code": "ACCESS", "description": "A request for access to a system, application, shared resource, or permission set.", "sort_order": 3},
        ]
        for tt in ticket_types:
            TicketType.objects.get_or_create(code=tt["code"], defaults={"name": tt["name"], "description": tt["description"], "sort_order": tt["sort_order"]})

        # Seed Ticket Systems
        ticket_systems = [
            {"name": "Hardware", "code": "HARDWARE", "description": "Issues related to hardware.", "sort_order": 1},
            {"name": "Software", "code": "SOFTWARE", "description": "Issues related to software or software request.", "sort_order": 2},
            {"name": "Network", "code": "NETWORK", "description": "Issues related to network connectivity.", "sort_order": 3},
            {"name": "Email", "code": "EMAIL", "description": "Issues related to email systems.", "sort_order": 4},
            {"name": "General IT", "code": "GENERAL", "description": "Issues related to the General IT.", "sort_order": 5},
        ]
        for ts in ticket_systems:
            TicketSystem.objects.get_or_create(code=ts["code"], defaults={"name": ts["name"], "description": ts["description"], "sort_order": ts["sort_order"]})

        # Seed Ticket Priorities
        ticket_priorities = [
            {"name": "Low", "code": "LOW", "description": "Low priority issue.", "sort_order": 1},
            {"name": "Medium", "code": "MEDIUM", "description": "Medium priority issue.", "sort_order": 2},
            {"name": "High", "code": "HIGH", "description": "High priority issue.", "sort_order": 3},
        ]
        for tp in ticket_priorities:
            TicketPriority.objects.get_or_create(code=tp["code"], defaults={"name": tp["name"], "description": tp["description"], "sort_order": tp["sort_order"]})

        # Seed Ticket Statuses
        ticket_statuses = [
            {"name": "Open", "code": "OPEN", "description": "The ticket is open and awaiting action.", "is_closed": False, "sort_order": 1},
            {"name": "In Progress", "code": "IN_PROGRESS", "description": "Work on the ticket is in progress.", 	"is_closed": False, "sort_order": 2},
            {"name": "Closed", "code": "CLOSED", 	"description": 	"The ticket has been resolved and closed.", 	"is_closed": True, "sort_order": 3},
        ]
        for ts in ticket_statuses:
            TicketStatus.objects.get_or_create(code=ts["code"], defaults={"name": ts["name"], "description": ts["description"], "is_closed": ts["is_closed"], "sort_order": ts["sort_order"]})
    
def unseed_lookup_data(apps, schema_editor):
    TicketType = apps.get_model("tickets", "TicketType")
    TicketSystem = apps.get_model("tickets", "TicketSystem")
    TicketPriority = apps.get_model("tickets", "TicketPriority")
    TicketStatus = apps.get_model("tickets", "TicketStatus")

    TicketType.objects.filter(code__in=["INCIDENT", "SERVICE", "ACCESS"]).delete()
    TicketSystem.objects.filter(code__in=["HARDWARE", "SOFTWARE", "NETWORK", "EMAIL","GENERAL"]).delete()
    TicketPriority.objects.filter(code__in=["LOW", "MEDIUM", "HIGH"]).delete()
    TicketStatus.objects.filter(code__in=["OPEN", "IN_PROGRESS", "CLOSED"]).delete()
    
class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [migrations.RunPython(seed_lookup_data, unseed_lookup_data)]
