# Student Name: Cian O'Connor
# Student Number: x22109668
# Module: Final Year Project

# Generated by Django 6.0.1 on 2026-07-09 20:41

from django.db import migrations, models


def seed_cancelled_status(apps, schema_editor):
    TicketStatus = apps.get_model("tickets", "TicketStatus")
    TicketStatus.objects.get_or_create(
        code="CANCELLED",
        defaults={
            "name": "Cancelled",
            "description": "The ticket was cancelled before resolution.",
            "is_active": True,
            "is_closed": True,
            "sort_order": 4,
        },
    )


def unseed_cancelled_status(apps, schema_editor):
    TicketStatus = apps.get_model("tickets", "TicketStatus")
    TicketStatus.objects.filter(code="CANCELLED").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_alter_ticket_ticket_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolution_summary",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(seed_cancelled_status, unseed_cancelled_status),
    ]
