# Generated by Django 6.0.1 on 2026-07-19 17:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tickets", "0004_add_resolution_cancel_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketCategoryPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "predicted_category",
                    models.CharField(
                        choices=[
                            ("hardware", "Hardware"),
                            ("software", "Software"),
                            ("network", "Network"),
                            ("access", "Access"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                ("category_model_name", models.CharField(max_length=50)),
                ("category_model_version", models.CharField(max_length=64)),
                ("is_security_flagged", models.BooleanField(default=False)),
                (
                    "security_confidence",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "security_threshold",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                ("matched_keywords", models.CharField(blank=True, max_length=255)),
                (
                    "staff_override_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hardware", "Hardware"),
                            ("software", "Software"),
                            ("network", "Network"),
                            ("access", "Access"),
                        ],
                        max_length=20,
                    ),
                ),
                ("overridden_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "overridden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_category_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_prediction",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confidence__gte", 0.0), ("confidence__lte", 1.0)
                        ),
                        name="ml_prediction_confidence_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("security_confidence__isnull", True),
                            models.Q(
                                ("security_confidence__gte", 0.0),
                                ("security_confidence__lte", 1.0),
                            ),
                            _connector="OR",
                        ),
                        name="ml_security_confidence_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("security_threshold__gte", 0.0),
                            ("security_threshold__lte", 1.0),
                        ),
                        name="ml_security_threshold_range",
                    ),
                ],
            },
        ),
    ]
