# Generated by Django 6.0.1 on 2026-07-19 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketcategoryprediction",
            name="category_model_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="ticketcategoryprediction",
            name="category_model_version",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="ticketcategoryprediction",
            name="confidence",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ticketcategoryprediction",
            name="predicted_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("network", "Network"),
                    ("access", "Access"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticketcategoryprediction",
            name="security_threshold",
            field=models.FloatField(
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
