# Generated by Django 6.0.1 on 2026-07-19 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml", "0002_alter_ticketcategoryprediction_category_model_name_and_more"),
        ("tickets", "0004_add_resolution_cancel_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticketcategoryprediction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("overridden_at__isnull", True), ("staff_override_category", "")
                    ),
                    models.Q(
                        models.Q(("staff_override_category", ""), _negated=True),
                        ("overridden_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ml_override_category_timestamp_consistent",
            ),
        ),
    ]
